# coding: utf-8

"""
    Margin API

    API for estimating trade margins for orders

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.preorder_check_response import PreorderCheckResponse

class TestPreorderCheckResponse(unittest.TestCase):
    """PreorderCheckResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PreorderCheckResponse:
        """Test PreorderCheckResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PreorderCheckResponse`
        """
        model = PreorderCheckResponse()
        if include_optional:
            return PreorderCheckResponse(
                margin = 1.337,
                free_money = 1.337,
                total_free_money = 1.337,
                delta = 1.337,
                commission_charge_account_id = '',
                expected_commission = 1.337,
                new_orders_commission = 1.337,
                margin_check_passed = True,
                margin_structure = openapi_client.models.margin_structure.MarginStructure(
                    before = [
                        openapi_client.models.margin_structure_component.MarginStructureComponent(
                            asset = '', 
                            asset_type = 'regular', 
                            position = 1.337, 
                            price = 1.337, 
                            currency = '', 
                            crossrate = 1.337, 
                            leverage_rate = 1.337, 
                            margin = 1.337, 
                            conv_margin = 1.337, 
                            extreme_margin = 1.337, 
                            conv_extreme_margin = 1.337, 
                            effective_qtty = 1.337, )
                        ], 
                    after = [
                        openapi_client.models.margin_structure_component.MarginStructureComponent(
                            asset = '', 
                            asset_type = 'regular', 
                            position = 1.337, 
                            price = 1.337, 
                            currency = '', 
                            crossrate = 1.337, 
                            leverage_rate = 1.337, 
                            margin = 1.337, 
                            conv_margin = 1.337, 
                            extreme_margin = 1.337, 
                            conv_extreme_margin = 1.337, 
                            effective_qtty = 1.337, )
                        ], ),
                warnings = [
                    ''
                    ]
            )
        else:
            return PreorderCheckResponse(
        )
        """

    def testPreorderCheckResponse(self):
        """Test PreorderCheckResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
