# coding: utf-8

"""
    Margin API

    API for estimating trade margins for orders

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.preorder_api import PreorderApi


class TestPreorderApi(unittest.TestCase):
    """PreorderApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PreorderApi()

    def tearDown(self) -> None:
        pass

    def test_preorder_account_id_get(self) -> None:
        """Test case for preorder_account_id_get

        Estimate trade margin for one order
        """
        pass

    def test_preorder_account_id_post(self) -> None:
        """Test case for preorder_account_id_post

        Estimate trade margin for list of orders
        """
        pass


if __name__ == '__main__':
    unittest.main()
