# coding: utf-8

"""
    Margin API

    API for estimating trade margins for orders

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.preorder_account_id_post_request_orders_data_inner import PreorderAccountIdPostRequestOrdersDataInner

class TestPreorderAccountIdPostRequestOrdersDataInner(unittest.TestCase):
    """PreorderAccountIdPostRequestOrdersDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PreorderAccountIdPostRequestOrdersDataInner:
        """Test PreorderAccountIdPostRequestOrdersDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PreorderAccountIdPostRequestOrdersDataInner`
        """
        model = PreorderAccountIdPostRequestOrdersDataInner()
        if include_optional:
            return PreorderAccountIdPostRequestOrdersDataInner(
                price = 45.31,
                quantity = 89.25,
                symbol_id = 'EUR/USD.EXANTE'
            )
        else:
            return PreorderAccountIdPostRequestOrdersDataInner(
                quantity = 89.25,
                symbol_id = 'EUR/USD.EXANTE',
        )
        """

    def testPreorderAccountIdPostRequestOrdersDataInner(self):
        """Test PreorderAccountIdPostRequestOrdersDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
