# coding: utf-8

"""
    Preorder Margin API

    API for estimating trade margins for orders

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.preorder_check_post_request_orders_data_inner import PreorderCheckPostRequestOrdersDataInner

class TestPreorderCheckPostRequestOrdersDataInner(unittest.TestCase):
    """PreorderCheckPostRequestOrdersDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PreorderCheckPostRequestOrdersDataInner:
        """Test PreorderCheckPostRequestOrdersDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PreorderCheckPostRequestOrdersDataInner`
        """
        model = PreorderCheckPostRequestOrdersDataInner()
        if include_optional:
            return PreorderCheckPostRequestOrdersDataInner(
                price = 45.31,
                quantity = 89.25,
                symbol_id = 'EUR/USD.EXANTE'
            )
        else:
            return PreorderCheckPostRequestOrdersDataInner(
                quantity = 89.25,
                symbol_id = 'EUR/USD.EXANTE',
        )
        """

    def testPreorderCheckPostRequestOrdersDataInner(self):
        """Test PreorderCheckPostRequestOrdersDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
