image: nexus.dev.zorg.sh:5000/xnt/build/npm:18

variables:
  OPENAPI_GENERATOR_VERSION: 7.9.0
  SPEC_FILE: openapi.yaml
  GIT_USER_EMAIL: "gitlab-ci@exante.eu"
  GIT_USER_NAME: "GitLab CI"
  ERLANG_BRANCH: erlang_server_test
  PYTHON_BRANCH: python_client_test

stages:
  - validate
  - extract_version
  - generate

validate:
  stage: validate
  image: openapitools/openapi-generator-cli:v${OPENAPI_GENERATOR_VERSION}
  tags:
    - docker
  script:
    - java -jar /opt/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar validate -i ${SPEC_FILE}

extract_version:
  stage: extract_version
  tags:
    - docker
  script:
    - npm install js-yaml
    - VERSION=$(node -e "
      const yaml = require('js-yaml');
      const fs = require('fs');
      const spec = yaml.load(fs.readFileSync('${SPEC_FILE}', 'utf8'));
      console.log(spec.info.version);
      ")
    - echo "VERSION=${VERSION}" >> version.env
  artifacts:
    reports:
      dotenv: version.env

generate-erlang:
  stage: generate
  tags:
    - docker
  image: openapitools/openapi-generator-cli:v${OPENAPI_GENERATOR_VERSION}
  variables:
    GENERATOR_NAME: erlang-server
    OUTPUT_DIR: ./generated-erlang
    TEMPLATE_DIR: ./template/erlang-api
  script:
    - java -jar /opt/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate
      -i ${SPEC_FILE}
      -g ${GENERATOR_NAME}
      -o ${OUTPUT_DIR}
      -c ./config.yaml
      --openapi-generator-ignore-list "src/openapi_auth.erl"
  artifacts:
    paths:
      - ${OUTPUT_DIR}
  dependencies:
    - validate

generate-python:
  stage: generate
  tags:
    - docker
  image: openapitools/openapi-generator-cli:v${OPENAPI_GENERATOR_VERSION}
  variables:
    GENERATOR_NAME: python
    OUTPUT_DIR: ./generated-python
  script:
    - java -jar /opt/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate
      -i ${SPEC_FILE}
      -g ${GENERATOR_NAME}
      -o ${OUTPUT_DIR}
  artifacts:
    paths:
      - ${OUTPUT_DIR}
  dependencies:
    - validate 