image: nexus.dev.zorg.sh:5000/xnt/build/npm:18

variables:
  OPENAPI_GENERATOR_VERSION: 7.9.0
  SPEC_FILE: openapi.yaml
  GIT_USER_EMAIL: "gitlab-ci@exante.eu"
  GIT_USER_NAME: "GitLab CI"
  ERLANG_BRANCH: erlang_server
  PYTHON_BRANCH: python_client
  GIT_REPOSITORY: "git@gitlab.exan.tech:erlang/premargo_api.git"
  MAIN_BRANCH: "master"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_COMMIT_BRANCH == $MAIN_BRANCH
      when: always
    - when: never

stages:
  - validate
  - extract_version
  - generate
  - swagger_ui
  - push

validate:
  stage: validate
  image: openapitools/openapi-generator-cli:v${OPENAPI_GENERATOR_VERSION}
  tags:
    - docker
  script:
    - java -jar /opt/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar validate -i ${SPEC_FILE}
  rules:
    - when: always  # This job runs on every pipeline

extract_version:
  stage: extract_version
  tags:
    - docker
  script:
    - npm install js-yaml
    - VERSION=$(node -e "
      const yaml = require('js-yaml');
      const fs = require('fs');
      const spec = yaml.load(fs.readFileSync('${SPEC_FILE}', 'utf8'));
      console.log(spec.info.version);
      ")
    - echo "VERSION=${VERSION}" >> version.env
  artifacts:
    reports:
      dotenv: version.env
  rules:
    - if: $CI_COMMIT_BRANCH == $MAIN_BRANCH
      when: always
    - when: never

generate-erlang:
  stage: generate
  tags:
    - docker
  image: openapitools/openapi-generator-cli:v${OPENAPI_GENERATOR_VERSION}
  variables:
    GENERATOR_NAME: erlang-server
    OUTPUT_DIR: ./generated-erlang
    TEMPLATE_DIR: ./template/erlang-api
  script:
    - java -jar /opt/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate
      -i ${SPEC_FILE}
      -g ${GENERATOR_NAME}
      -o ${OUTPUT_DIR}
      -c ./config.yaml
      --openapi-generator-ignore-list "src/openapi_auth.erl"
  artifacts:
    paths:
      - ${OUTPUT_DIR}
  dependencies:
    - validate
  rules:
    - if: $CI_COMMIT_BRANCH == $MAIN_BRANCH
      when: always
    - when: never

generate-python:
  stage: generate
  tags:
    - docker
  image: openapitools/openapi-generator-cli:v${OPENAPI_GENERATOR_VERSION}
  variables:
    GENERATOR_NAME: python
    OUTPUT_DIR: ./generated-python
  script:
    - java -jar /opt/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate
      -i ${SPEC_FILE}
      -g ${GENERATOR_NAME}
      -o ${OUTPUT_DIR}
  artifacts:
    paths:
      - ${OUTPUT_DIR}
  dependencies:
    - validate
  rules:
    - if: $CI_COMMIT_BRANCH == $MAIN_BRANCH
      when: always
    - when: never

generate_swagger_ui:
  stage: swagger_ui
  tags:
    - docker
  needs:
    - generate-erlang
    - generate-python
  script:
    - cd generated-erlang
    - mkdir -p priv/swagger
    - cd priv/swagger
    - curl -L https://github.com/swagger-api/swagger-ui/archive/refs/tags/v5.11.8.tar.gz | tar xz --strip-components=2 swagger-ui-5.11.8/dist/
    - sed -i 's|"https://petstore.swagger.io/v2/swagger.json"|window.location.origin + "/api-docs/openapi.json"|g' swagger-initializer.js
    - rm -rf .git* *.md
    - cd ../..
  artifacts:
    paths:
      - generated-erlang/
  rules:
    - if: $CI_COMMIT_BRANCH == $MAIN_BRANCH
      when: always
    - when: never

push_erlang:
  stage: push
  image: bitnami/git:latest
  needs:
    - generate_swagger_ui
    - extract_version
  before_script:
    - |
      git config --global user.email "${GIT_USER_EMAIL}"
      git config --global user.name "${GIT_USER_NAME}"
      if [ ! -f "$SSH_PRIVATE_KEY" ]; then echo "SSH_PRIVATE_KEY file not found at: $SSH_PRIVATE_KEY"; exit 1; fi
      echo "Reading SSH key from file: $SSH_PRIVATE_KEY"
      eval $(ssh-agent -s)
      mkdir -p ~/.ssh
      chmod 700 ~/.ssh
      base64 -d "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      ssh-add ~/.ssh/id_rsa 2>&1 || { echo "Failed to add SSH key"; exit 1; }
      ssh-add -l || echo "No keys found in ssh-agent"
      ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
      chmod 644 ~/.ssh/known_hosts
      # Change remote URL from HTTPS to SSH
      git remote set-url origin "${GIT_REPOSITORY}"
  script:
    - git checkout ${ERLANG_BRANCH} || git checkout -b ${ERLANG_BRANCH}
    - mkdir -p temp_backup
    - cp -rv generated-erlang/* temp_backup/
    - find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name 'temp_backup' -exec rm -rf {} +
    - mv temp_backup/* .
    - rm -rf temp_backup
    - git add .
    - git commit -m "Update generated Erlang server code from OpenAPI spec erl-${VERSION}" || echo "No changes to commit"
    - git tag -a "erl-${VERSION}" -m "Release erl-${VERSION}" || echo "Tag already exists"
    - git push origin ${ERLANG_BRANCH} || echo "Branch is up to date"
    - git push origin "erl-${VERSION}" || echo "Tag already pushed"
  variables:
    GIT_STRATEGY: clone
  rules:
    - if: $CI_COMMIT_BRANCH == $MAIN_BRANCH
      when: always
    - when: never

push_python:
  stage: push
  tags:
    - docker
  image: bitnami/git:latest
  needs:
    - generate-python
    - extract_version
  before_script:
    - |
      git config --global user.email "${GIT_USER_EMAIL}"
      git config --global user.name "${GIT_USER_NAME}"
      if [ ! -f "$SSH_PRIVATE_KEY" ]; then echo "SSH_PRIVATE_KEY file not found at: $SSH_PRIVATE_KEY"; exit 1; fi
      echo "Reading SSH key from file: $SSH_PRIVATE_KEY"
      eval $(ssh-agent -s)
      mkdir -p ~/.ssh
      chmod 700 ~/.ssh
      base64 -d "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      ssh-add ~/.ssh/id_rsa 2>&1 || { echo "Failed to add SSH key"; exit 1; }
      ssh-add -l || echo "No keys found in ssh-agent"
      ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
      chmod 644 ~/.ssh/known_hosts
      # Change remote URL from HTTPS to SSH
      git remote set-url origin "${GIT_REPOSITORY}"
  script:
    - git checkout ${PYTHON_BRANCH} || git checkout -b ${PYTHON_BRANCH}
    - mkdir -p temp_backup
    - cp -rv generated-python/* temp_backup/
    - find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name 'temp_backup' -exec rm -rf {} +
    - mv temp_backup/* .
    - rm -rf temp_backup
    - git add .
    - git commit -m "Update generated Python client code from OpenAPI spec py-${VERSION}" || echo "No changes to commit"
    - git tag -a "py-${VERSION}" -m "Release py-${VERSION}" || echo "Tag already exists"
    - git push origin ${PYTHON_BRANCH} || echo "Branch is up to date"
    - git push origin "py-${VERSION}" || echo "Tag already pushed"
  variables:
    GIT_STRATEGY: clone
  rules:
    - if: $CI_COMMIT_BRANCH == $MAIN_BRANCH
      when: always
    - when: never