additionalProperties:
  artifactId: erlang-generated
  serializableModel: "true"
  dateLibrary: java8
templateDir: template/erlang-api
files:
  swagger.mustache:
    folder: src
    templateType: SupportingFiles
    destinationFilename: openapi_swagger.erl
