openapi: 3.0.0
info:
  title: Preorder Margin API
  description: API for estimating trade margins for orders
  version: 0.0.1
  
servers:
  - url: /api
    description: Default API server

tags:
  - name: preorder
    description: Account operations for margin calculations

paths:
  /v1.0/preorder_margin/{account_id}:
    get:
      tags:
        - preorder
      summary: Estimate trade margin for one order
      operationId: preorder_check_get
      parameters:
        - in: path
          name: account_id
          description: Account Id
          required: true
          schema:
            type: string
            default: FBB1234.001
          example: FBB1234.001
        - in: query
          name: symbolId
          required: true
          schema:
            type: string
          example: EUR/USD.EXANTE
        - in: query
          name: quantity
          required: true
          schema:
            type: number
            format: float
          example: "35.68"
        - in: query
          name: currency
          description: Currency code
          required: false
          schema:
            type: string
            default: EUR
        - in: query
          name: price
          required: false
          schema:
            type: number
            format: float
          example: "99.71"
        - in: query
          name: showMarginStructure
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Successful margin check operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PreorderCheckResponse'
        '400':
          description: Invalid input parameters
        '404':
          description: Account not found
    
    post:
      tags:
        - preorder
      summary: Estimate trade margin for list of orders
      operationId: preorder_check_post
      parameters:
        - in: path
          name: account_id
          description: Account Id
          required: true
          schema:
            type: string
            default: FBB1234.001
          example: FBB1234.001
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - ordersData
              properties:
                currency:
                  type: string
                  default: EUR
                  description: Currency code
                ordersData:
                  type: array
                  items:
                    type: object
                    required:
                      - quantity
                      - symbolId
                    properties:
                      price:
                        type: number
                        format: float
                        example: "45.31"
                      quantity:
                        type: number
                        format: float
                        example: "89.25"
                      symbolId:
                        type: string
                        example: EUR/USD.EXANTE
                showMarginStructure:
                  type: boolean
                  default: false
      responses:
        '200':
          description: Successful margin check operation for multiple orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PreorderCheckResponse'
        '400':
          description: Invalid input parameters
        '404':
          description: Account not found

components:
  schemas:
    MarginComponent:
      type: object
      required:
        - type
        - asset
        - assetType
        - position
        - price
        - currency
        - currencyLeverageRateLong
        - currencyLeverageRateShort
        - crossrate
        - leverageRate
        - margin
        - convertedMargin
        - extremeMargin
        - convertedExtremeMargin
        - effectiveQtty
      properties:
        type:
          type: string
          enum: [margin]
        asset:
          type: string
          description: Asset identifier
        assetType:
          type: string
          enum: [regular, order_short, order_long]
        position:
          type: string
          pattern: '^-?\d*\.?\d+$'
        price:
          type: string
          pattern: '^-?\d*\.?\d+$'
        currency:
          type: string
        currencyLeverageRateLong:
          type: string
          pattern: '^-?\d*\.?\d+$'
        currencyLeverageRateShort:
          type: string
          pattern: '^-?\d*\.?\d+$'
        crossrate:
          type: string
          pattern: '^-?\d*\.?\d+$'
        leverageRate:
          type: string
          pattern: '^-?\d*\.?\d+$'
        margin:
          type: string
          pattern: '^-?\d*\.?\d+$'
        convertedMargin:
          type: string
          pattern: '^-?\d*\.?\d+$'
        extremeMargin:
          type: string
          pattern: '^-?\d*\.?\d+$'
        convertedExtremeMargin:
          type: string
          pattern: '^-?\d*\.?\d+$'
        effectiveQtty:
          type: string
          pattern: '^-?\d*\.?\d+$'

    CurrencyOrderMarginComponent:
      type: object
      required:
        - type
        - currency
        - longQuantity
        - shortQuantity
        - longMargin
        - shortMargin
        - margin
        - convertedMargin
        - crossrate
        - currencyLeverageRateShort
        - currencyLeverageRateLong
      properties:
        type:
          type: string
          enum: [currency_order_margin]
        currency:
          type: string
        longQuantity:
          type: string
          pattern: '^-?\d*\.?\d+$'
        shortQuantity:
          type: string
          pattern: '^-?\d*\.?\d+$'
        longMargin:
          type: string
          pattern: '^-?\d*\.?\d+$'
        shortMargin:
          type: string
          pattern: '^-?\d*\.?\d+$'
        margin:
          type: string
          pattern: '^-?\d*\.?\d+$'
        convertedMargin:
          type: string
          pattern: '^-?\d*\.?\d+$'
        crossrate:
          type: string
          pattern: '^-?\d*\.?\d+$'
        currencyLeverageRateShort:
          type: string
          pattern: '^-?\d*\.?\d+$'
        currencyLeverageRateLong:
          type: string
          pattern: '^-?\d*\.?\d+$'

    ScanningRiskComponent:
      type: object
      required:
        - type
        - underlying
        - currency
        - assetsList
        - assetsLongList
        - assetsShortList
        - leverageRate
        - margin
        - convertedMargin
        - extremeMargin
        - convertedExtremeMargin
      properties:
        type:
          type: string
          enum: [scanning_risk]
        underlying:
          type: string
        currency:
          type: string
        assetsList:
          type: array
          items:
            type: string
        assetsLongList:
          type: array
          items:
            type: string
        assetsShortList:
          type: array
          items:
            type: string
        leverageRate:
          type: string
          pattern: '^-?\d*\.?\d+$'
        margin:
          type: string
          pattern: '^-?\d*\.?\d+$'
        convertedMargin:
          type: string
          pattern: '^-?\d*\.?\d+$'
        extremeMargin:
          type: string
          pattern: '^-?\d*\.?\d+$'
        convertedExtremeMargin:
          type: string
          pattern: '^-?\d*\.?\d+$'

    InterspreadMarginComponent:
      type: object
      required:
        - type
        - underlying
        - currency
        - assetsList
        - assetsLongList
        - assetsShortList
        - spreads
        - leverageRate
        - margin
        - convertedMargin
        - extremeMargin
        - convertedExtremeMargin
      properties:
        type:
          type: string
          enum: [interspread_margin]
        underlying:
          type: string
        currency:
          type: string
        assetsList:
          type: array
          items:
            type: string
        assetsLongList:
          type: array
          items:
            type: string
        assetsShortList:
          type: array
          items:
            type: string
        spreads:
          type: object
          required:
            - frontFront
            - frontBack
            - backBack
          properties:
            frontFront:
              type: string
              pattern: '^-?\d*\.?\d+$'
            frontBack:
              type: string
              pattern: '^-?\d*\.?\d+$'
            backBack:
              type: string
              pattern: '^-?\d*\.?\d+$'
        leverageRate:
          type: string
          pattern: '^-?\d*\.?\d+$'
        margin:
          type: string
          pattern: '^-?\d*\.?\d+$'
        convertedMargin:
          type: string
          pattern: '^-?\d*\.?\d+$'
        extremeMargin:
          type: string
          pattern: '^-?\d*\.?\d+$'
        convertedExtremeMargin:
          type: string
          pattern: '^-?\d*\.?\d+$'

    IntercommodityCreditComponent:
      type: object
      required:
        - type
        - underlying1
        - underlying2
        - currency
        - spreads
        - leverageRate
        - margin
        - convertedMargin
      properties:
        type:
          type: string
          enum: [intercommodity_credit]
        underlying1:
          type: string
        underlying2:
          type: string
        currency:
          type: string
        spreads:
          type: object
          required:
            - frontFront
            - frontBack
            - backFront
            - backBack
          properties:
            frontFront:
              type: string
              pattern: '^-?\d*\.?\d+$'
            frontBack:
              type: string
              pattern: '^-?\d*\.?\d+$'
            backFront:
              type: string
              pattern: '^-?\d*\.?\d+$'
            backBack:
              type: string
              pattern: '^-?\d*\.?\d+$'
        leverageRate:
          type: string
          pattern: '^-?\d*\.?\d+$'
        margin:
          type: string
          pattern: '^-?\d*\.?\d+$'
        convertedMargin:
          type: string
          pattern: '^-?\d*\.?\d+$'

    OptionMinimumComponent:
      type: object
      required:
        - type
        - underlying
        - currency
        - assetsList
        - assetsLongList
        - assetsShortList
        - leverageRate
        - margin
        - convertedMargin
        - extremeMargin
        - convertedExtremeMargin
      properties:
        type:
          type: string
          enum: [option_minimum]
        underlying:
          type: string
        currency:
          type: string
        assetsList:
          type: array
          items:
            type: string
        assetsLongList:
          type: array
          items:
            type: string
        assetsShortList:
          type: array
          items:
            type: string
        leverageRate:
          type: string
          pattern: '^-?\d*\.?\d+$'
        margin:
          type: string
          pattern: '^-?\d*\.?\d+$'
        convertedMargin:
          type: string
          pattern: '^-?\d*\.?\d+$'
        extremeMargin:
          type: string
          pattern: '^-?\d*\.?\d+$'
        convertedExtremeMargin:
          type: string
          pattern: '^-?\d*\.?\d+$'

    BlockedFundsComponent:
      type: object
      required:
        - type
        - reason
        - currency
        - margin
        - convertedMargin
      properties:
        type:
          type: string
          enum: [blocked_funds]
        reason:
          type: string
        currency:
          type: string
        margin:
          type: string
          pattern: '^-?\d*\.?\d+$'
        convertedMargin:
          type: string
          pattern: '^-?\d*\.?\d+$'

    OrderMarginComponent:
      type: object
      required:
        - type
        - currency
        - asset
        - margin
        - convertedMargin
      properties:
        type:
          type: string
          enum: [order_margin]
        currency:
          type: string
        asset:
          type: string
        margin:
          type: string
          pattern: '^-?\d*\.?\d+$'
        convertedMargin:
          type: string
          pattern: '^-?\d*\.?\d+$'

    MarginStructure:
      type: object
      required:
        - before
        - after
      properties:
        before:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/MarginComponent'
              - $ref: '#/components/schemas/CurrencyOrderMarginComponent'
              - $ref: '#/components/schemas/ScanningRiskComponent'
              - $ref: '#/components/schemas/InterspreadMarginComponent'
              - $ref: '#/components/schemas/IntercommodityCreditComponent'
              - $ref: '#/components/schemas/OptionMinimumComponent'
              - $ref: '#/components/schemas/BlockedFundsComponent'
              - $ref: '#/components/schemas/OrderMarginComponent'
        after:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/MarginComponent'
              - $ref: '#/components/schemas/CurrencyOrderMarginComponent'
              - $ref: '#/components/schemas/ScanningRiskComponent'
              - $ref: '#/components/schemas/InterspreadMarginComponent'
              - $ref: '#/components/schemas/IntercommodityCreditComponent'
              - $ref: '#/components/schemas/OptionMinimumComponent'
              - $ref: '#/components/schemas/BlockedFundsComponent'
              - $ref: '#/components/schemas/OrderMarginComponent'

    PreorderCheckResponse:
      type: object
      required:
        - margin
        - freeMoney
        - totalFreeMoney
        - delta
        - commissionChargeAccountId
        - expectedCommission
        - newOrdersCommission
        - marginCheckPassed
        - marginStructure
        - warnings
      properties:
        margin:
          type: string
          pattern: '^-?\d*\.?\d+$'
          description: Required margin for the orders
        freeMoney:
          type: string
          pattern: '^-?\d*\.?\d+$'
          description: Available free money
        totalFreeMoney:
          type: string
          pattern: '^-?\d*\.?\d+$'
          description: Total available free money
        delta:
          type: string
          pattern: '^-?\d*\.?\d+$'
          description: Margin change
        commissionChargeAccountId:
          type: string
          description: Account ID for commission charges
        expectedCommission:
          type: string
          pattern: '^-?\d*\.?\d+$'
          description: Expected commission for the orders
        newOrdersCommission:
          type: string
          pattern: '^-?\d*\.?\d+$'
          description: Commission for new orders
        marginCheckPassed:
          type: boolean
          description: Whether the margin check passed
        marginStructure:
          $ref: '#/components/schemas/MarginStructure'
        warnings:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: Map of asset identifiers to their warning messages
        reason:
          type: string
          enum: [close_only, insufficient_margin, insufficient_commission, all_checks_passed]
          description: Reason for the margin check result

  securitySchemes: {}