openapi: 3.0.0
info:
  title: Margin API
  description: API for estimating trade margins for orders
  version: 1.0.0
  
servers:
  - url: /api/v2.0
    description: Default server

tags:
  - name: preorder
    description: Account operations for margin calculations

paths:
  /preorder/{account_id}
    get:
      tags:
        - preorder
      summary: Estimate trade margin for one order
      parameters:
        - in: path
          name: account_id
          description: Account Id
          required: true
          schema:
            type: string
            default: FBB1234.001
          example: FBB1234.001
        - in: query
          name: symbolId
          required: true
          schema:
            type: string
          example: EUR/USD.EXANTE
        - in: query
          name: quantity
          required: true
          schema:
            type: number
            format: double
          example: "35.68"
        - in: query
          name: currency
          description: Currency code
          required: false
          schema:
            type: string
            default: EUR
        - in: query
          name: price
          required: false
          schema:
            type: number
            format: double
          example: "99.71"
        - in: query
          name: showMarginStructure
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Successful margin check operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PreorderCheckResponse'
        '400':
          description: Invalid input parameters
        '404':
          description: Account not found
    
    post:
      tags:
        - preorder
      summary: Estimate trade margin for list of orders
      parameters:
        - in: path
          name: account_id
          description: Account Id
          required: true
          schema:
            type: string
            default: FBB1234.001
          example: FBB1234.001
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - ordersData
              properties:
                currency:
                  type: string
                  default: EUR
                  description: Currency code
                ordersData:
                  type: array
                  items:
                    type: object
                    required:
                      - quantity
                      - symbolId
                    properties:
                      price:
                        type: number
                        format: double
                        example: "45.31"
                      quantity:
                        type: number
                        format: double
                        example: "89.25"
                      symbolId:
                        type: string
                        example: EUR/USD.EXANTE
                showMarginStructure:
                  type: boolean
                  default: false
      responses:
        '200':
          description: Successful margin check operation for multiple orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PreorderCheckResponse'
        '400':
          description: Invalid input parameters
        '404':
          description: Account not found

components:
  schemas:
    MarginStructureComponent:
      type: object
      properties:
        asset:
          type: string
          description: Asset identifier
        assetType:
          type: string
          enum: [regular, order_short, order_long]
        position:
          type: number
          format: double
        price:
          type: number
          format: double
        currency:
          type: string
        crossrate:
          type: number
          format: double
        leverageRate:
          type: number
          format: double
        margin:
          type: number
          format: double
        convMargin:
          type: number
          format: double
        extremeMargin:
          type: number
          format: double
        convExtremeMargin:
          type: number
          format: double
        effectiveQtty:
          type: number
          format: double

    MarginStructure:
      type: object
      properties:
        before:
          type: array
          items:
            $ref: '#/components/schemas/MarginStructureComponent'
        after:
          type: array
          items:
            $ref: '#/components/schemas/MarginStructureComponent'

    PreorderCheckResponse:
      type: object
      properties:
        margin:
          type: number
          format: double
          description: Required margin for the orders
        freeMoney:
          type: number
          format: double
          description: Available free money
        totalFreeMoney:
          type: number
          format: double
          description: Total available free money
        delta:
          type: number
          format: double
          description: Margin change
        commissionChargeAccountId:
          type: string
          description: Account ID for commission charges
        expectedCommission:
          type: number
          format: double
          description: Expected commission for the orders
        newOrdersCommission:
          type: number
          format: double
          description: Commission for new orders
        marginCheckPassed:
          type: boolean
          description: Whether the margin check passed
        marginStructure:
          $ref: '#/components/schemas/MarginStructure'
        warnings:
          type: array
          items:
            type: string
          description: List of warnings if any

  securitySchemes: {}