# coding: utf-8

# flake8: noqa
"""
    OpenAPI Template

    There is a new description.

    The version of the OpenAPI document: 1.0.5a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.api_response import ApiResponse
from openapi_client.models.category import Category
from openapi_client.models.order import Order
from openapi_client.models.pet import Pet
from openapi_client.models.tag import Tag
