# coding: utf-8

# flake8: noqa
"""
    Margin API

    API for estimating trade margins for orders

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.margin_structure import MarginStructure
from openapi_client.models.margin_structure_component import MarginStructureComponent
from openapi_client.models.preorder_account_id_post_request import PreorderAccountIdPostRequest
from openapi_client.models.preorder_account_id_post_request_orders_data_inner import PreorderAccountIdPostRequestOrdersDataInner
from openapi_client.models.preorder_check_response import PreorderCheckResponse
