# coding: utf-8

# flake8: noqa

"""
    Margin API

    API for estimating trade margins for orders

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.preorder_api import PreorderApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.margin_structure import MarginStructure
from openapi_client.models.margin_structure_component import MarginStructureComponent
from openapi_client.models.preorder_check_post_request import PreorderCheckPostRequest
from openapi_client.models.preorder_check_post_request_orders_data_inner import PreorderCheckPostRequestOrdersDataInner
from openapi_client.models.preorder_check_response import PreorderCheckResponse
